"use client";

import { AlertDialog as AlertDialogPrimitive } from "radix-ui";
import { AlertCircle, Loader2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import OutlinedButton from "@/components/common/OutlinedButton";

export default function CancelFollowUpDialog({ open, businessName, loading, onOpenChange, onConfirm }: { open: boolean; businessName: string; loading?: boolean; onOpenChange: (open: boolean) => void; onConfirm: () => void }) {
  return <AlertDialogPrimitive.Root open={open} onOpenChange={(next) => { if (!loading) onOpenChange(next); }}><AlertDialogPrimitive.Portal><AlertDialogPrimitive.Overlay className="fixed inset-0 z-50 bg-black/40 backdrop-blur-[2px]" /><AlertDialogPrimitive.Content className="fixed left-1/2 top-1/2 z-50 w-[calc(100%-2rem)] max-w-[430px] -translate-x-1/2 -translate-y-1/2 rounded-2xl border border-red-200 bg-white p-6 shadow-2xl outline-none"><button type="button" onClick={() => onOpenChange(false)} disabled={loading} aria-label="Close" className="absolute right-4 top-4 rounded-lg p-1 text-[#94a3b8] hover:bg-[#f1f5f9]"><X className="size-4" /></button><div className="flex items-start gap-4"><div className="flex size-11 shrink-0 items-center justify-center rounded-xl border border-red-200 bg-red-50 text-red-600"><AlertCircle className="size-5" /></div><div><AlertDialogPrimitive.Title className="text-base font-bold text-red-950">Cancel follow-up?</AlertDialogPrimitive.Title><AlertDialogPrimitive.Description className="mt-2 text-sm leading-relaxed text-[#475569]">This will cancel the follow-up for <span className="font-semibold text-[#0f172a]">&ldquo;{businessName}&rdquo;</span>. This action cannot be undone.</AlertDialogPrimitive.Description></div></div><div className="mt-6 flex justify-end gap-2.5"><AlertDialogPrimitive.Cancel asChild><OutlinedButton type="button" disabled={loading} className="h-10 rounded-xl">Keep follow-up</OutlinedButton></AlertDialogPrimitive.Cancel><AlertDialogPrimitive.Action asChild><Button type="button" onClick={onConfirm} disabled={loading} className="h-10 rounded-xl bg-[#d92d20] text-white hover:bg-[#b42318]">{loading ? <><Loader2 className="size-4 animate-spin" /> Cancelling...</> : "Cancel follow-up"}</Button></AlertDialogPrimitive.Action></div></AlertDialogPrimitive.Content></AlertDialogPrimitive.Portal></AlertDialogPrimitive.Root>;
}
